// Code generated by goctl. DO NOT EDIT.

export interface Status {
  code: number
  msg: string
}

export interface SignInReq {
  authType: "phone" | "email" | "wechat"
  authValue: string
  password?: string
  options?: Array<string>
}

export interface SignInResp {
  status: Status
  accessToken: string
  accessExpire: number
}

export interface SetPasswordReq {
  password: string
}

export interface SetPasswordResp {
  status: Status
}

export interface SendVerifyCodeReq {
  authType: string
  authValue: string
}

export interface SendVerifyCodeResp {
  status: Status
}

