// Code generated by goctl. DO NOT EDIT.

export interface Status {
	code: number
	msg: string
}

export interface SignInReq {
	authType: "phone" | "email" | "wechat"
	authValue: string
	password?: string
	options?: Array<string>
}

export interface SignInResp {
	code: number
	msg: string
	accessToken: string
	accessExpire: number
}

