export const enum Pictures {
  NoData = "https://static.xhpolaris.com/nodata.png",
  ProfileBackground = "https://static.xhpolaris.com/profile_background.png",
  NoCatHere = "/static/images/no_cat_here.png",
  NoMore = "/static/images/nomore.png"
}

export const enum Icons {
  Location = "/static/images/location.png",
  Search = "/static/images/search.png",
  DownBlack = "/static/images/down-black.png",
  UpBlack = "/static/images/up-black.png",
  NewImage = "/static/images/add.png",
  Message = "/static/images/message-black.png",
  Collection = "/static/images/collection-grey.png",
  Delete = "/static/images/delete.png",
  Guide = "/static/images/guide.png",
  GoBack = "/static/images/left-black.png",
  Cancel = "/static/images/cancel.png",
  Tag = "/static/images/tag.png",
  Cam = "/static/images/campus_cat.png",
  View = "/static/images/view_the_illustration.png",
  Plan_PlanTag = "/static/images/plan/plan_tag.png",
  GoToPath_Tag = "/static/images/plan/GoToPath_heart_tag.png",
  GoToArrow = "/static/images/plan/GoToPath_right_arrow.png",
  CatExample = "/static/images/cat-example.png",
  LittleFish = "/static/images/Little_Fish.png",
  Frame = "/static/images/Frame.png",
  DialogBox = "/static/images/dialog-box.png",
  State_Frame = "/static/images/state-frame.png",
  Task_Pic = "/static/images/task-pic.png",
  Pic_Left = "/static/images/pic-left.png",
  Pic_Right = "/static/images/pic-right.png"
}

export const enum Pages {
  Plan = "/pages/plan/plan",
  FirstPage = "/pages/first-page/first-page",
  Cat = "/pages/cat/cat",
  Post = "/pages/post/post",
  WebView = "/pages/web-frame/web-frame",
  Profile = "/pages/profile/profile",
  ChooseCat = "/pages/draft/choose-cat/choose-cat",
  Community = "/pages/community/community",
  World = "/pages/world/world",
  DraftPost = "/pages/draft/draft-post",
  DraftMoment = "/pages/draft/draft-moment",
  DraftPlan = "/pages/draft/draft-plan",
  DraftNav = "/pages/draft/draft-nav/draft-nav",
  DraftTest = "/pages/draft/test",
  Collection = "/pages/collection/collection",
  Moment = "/pages/moment/moment",
  SchoolSelect = "/pages/school-select/school-select",
  Search = "/pages/search/search",
  DraftImage = "/pages/draft/draft-image/draft-image",
  MyPublish = "/pages/profile/my-publish/my-publish",
  Message = "/pages/message/message",
  Person = "/pages/profile/personal-info/personal-info",
  EditInfo = "/pages/profile/edit-info/edit-info"
}
